x = input('Digite algo:')
print(f'Você escreveu{x}')
print(type(x))
print(x.isnumeric())
print(x.isupper())
print(x.istitle())
print(x.isprintable())
print(x.islower())
print(x.isdigit())
print(x.isdecimal())
print(x.isalnum())
print(x.isidentifier())
print(x.isalpha())
print(x.isspace())

